name: swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: Didstopia/SwiftAction@v1.0.3
      with:
        swift-action: 'build'
    
    - uses: actions/checkout@v2
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-test-discovery
