name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery
