name: swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Didstopia/SwiftAction@1.0.3
      with:
        swift-action: 'build'
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-test-discovery
