name: swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: Didstopia/SwiftAction@v1.0.3
      with:
        swift-action: 'build -v --enable-test-discovery'
