name: swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: Didstopia/SwiftAction@v1.0.3
      with:
        swift-action: 'build -v --enable-test-discovery'
